This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file F:/Rodrigo Branco/workspace/dissertacaoMestrado/document.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file document.acn....done (280 entries accepted, 0 rejected).
Sorting entries.....done (2515 comparisons).
Generating output file document.acr....done (221 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
