This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file F:/workspaceEclipse/dissertacaoMestrado/document.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file document.acn....done (241 entries accepted, 0 rejected).
Sorting entries.....done (2264 comparisons).
Generating output file document.acr....done (201 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
